= Code of conduct
:page-pagination:


Все материалы на этом сайте являются открытыми и доступны всем. При их использовании ознакомьтесь с лицензией https://www.mozilla.org/en-US/MPL/2.0/[MPL-2.0], под которой распространяется проект.

IMPORTANT: Все материалы представленные на сайте должны быть составлены исключительно людьми! Не допускается публикация сгенерированных текстов, примеров кода, фото и видеоматериалов. Исключение делается только для демонстрации результатов работы ИИ в статьях про ИИ инструменты.

В проекте допускается использование "программистского сленга", транслитерации терминов, однако руссификация настоятельно не рекомендуется. Например, использование слова "нити" не будет одобрено маинтейнерами проекта, а слово "поток" лучше заменить на "тред". Аналогично будет предпочтительным использование слов "мержить" и "ребейзить" вместо попытки перевести это все на русский язык. Для тех, кто не разделяет подобный подход, в качестве компромисса предлагаем использование английских слов на латинице прямо в тексте.

При написании статей не допускается копипаста чужих текстов, материалов. Любые фото/видеоматериалы рекомендуется создавать самому: например, для диаграмм можно использовать https://draw.io[draw.io], в случае использования чужих материалов цитирование источников *обязательно*.

.Несколько рекомендаций по тому, как оформлять материал:
. Красивая диаграмма лучше текста
. Если пример использует несколько файлов, то в конце приложите ссылку на репозиторий, где все лежит вместе. Не забудьте приложить README с описанием, как с этим работать
. Если на английском языке используется иной термин, то обязательно укажите его

// TODO
WARNING: Переместить в контрибьютинг!!!

Мы рады любой _человеческой_ помощи с развитием проекта. Сообщить об ошибках можно как авторам статьи через указанные xref:authors.adoc[контакты связи], так и оформить ишую в https://github.com/progtech-course/book[проекте]. Для полноценного участия в проекте предлагаем сделать форк проекта, в котором будут произведены все изменения, после чего оформить пул реквест в проект. Если все будет успешно и вы захотите дальше продолжать помогать в развитии, то мы пригласим вас в разработчики проекта.
