= Папка dev
:page-pagination:
:page-authors: Иван Калинин
:description: Устройство папки /dev

В этой папке представлены различные девайсы, как блочного, так и символьного типа.

== Создание файлов устройств
Для создания такого рода файлов используется команда `mknod FILENAME TYPE MAJOR MINOR`. Параметр `TYPE` может принимать значения `b` или `c`, указывая тип девайса. Параметры `MAJOR` и `MINOR` кодируют какой конкретно девайс создается. Описания доступных комбинаций доступы в
https://www.kernel.org/doc/Documentation/admin-guide/devices.txt[документации ядра Linux].

== Character devices
/dev/null::
Null device. Любые данные записанные в него отбрасываются, а попытка прочитать его возвращает `EOF` символ.

TIP: Используйте этот файл, чтобы проигнорировать stderr или stdout

/dev/zero::
Аналогично `/dev/null` отбрасывает данные при записи, однако при чтении возвращает бесконечный стрим символов `\0`.

/dev/full::
Аналогично `/dev/zero` при чтении возвращает бесконечный стрим символов `\0`, однако при записи кидает ошибку переполнения диска (`ENOSPC`).

[.wrap,console]
----
$ echo 3 > /dev/full
echo: write error: no space left on device
----

/dev/random и /dev/urandom::
Оба файла используются для генерации псевдослучайных чисел. В качестве сида используется энтропия различных устройств системы. Как следствие, запись в эти устройства будет обновлять энтропию. Если ваша программа работает не в момент бутстрапа, то используйте `urandom`. Например, `std::random_device` https://en.cppreference.com/cpp/numeric/random/random_device/random_device#Notes[по умолчанию] использует именно `/dev/urandom`.

// TODO
[TIP.todo]
====
ссыль на рандомизацию и хэши?
====

WARNING: Устройства создают _бесконечный_ стрим случайных данных, поэтому всегда ограничивайте число считываемых данных. Например, через `head -c N`.

/dev/mem::
Это устройство представляет собой образ физической памяти (RAM). Адреса внутри этого устройства отражают реальные физические адреса в памяти.

/dev/kmem::
Аналогично прошлому устройству `kmem` представляется способ обращаться к памяти через файлы, однако `kmem` является представлением виртуальной памяти.

/dev/port::
Аналогично прошлым двум через это устройство можно обращаться напрямую к портам.

IMPORTANT: Доступ к последним трем устройствам может быть (скорее всего так и есть, если вы не собирали ядро вручную) ограничен на уровне конфигураций ядра Linux.

/dev/tty::
Терминальные устройства. Про них написано в xref:linux/ttys.adoc[следующей статье].

== Block devices

/dev/sd[a-z]::
Жесткие диски, использующие технологию SATA.

/dev/nvme[0-N]::
Жесткие диски, использующие технологию PCI.

NOTE: Под каждую партицию жесткого диска создается отдельное устройство с суффиксом `pN`, где N -- номер партиции внутри диска.

/dev/loop[0-N]::
Виртуальные девайсы, используемые для монтирования файловых систем не на физические устройства. Например, такие устройства можно связать с регулярным файлом и использовать такой файл как модель жесткого диска.

[,console]
----
$ dd if=/dev/zero of=file.img bs=1MiB count=10
$ sudo losetup /dev/loop4 file.img
$ sudo mkfs -t ext4 /dev/loop4
$ sudo mkdir /myloopdev
$ sudo mount /dev/loop4 /myloopdev
----

== Симлинки

/dev/fd::
Симлинка на `/proc/self/fd` -- папку с файловыми дескрипторами текущего процесса.

/dev/stdin::
Симлинка на `/proc/self/fd/0` -- стандартный поток ввода текущего процесса.

/dev/stdout::
Симлинка на `/proc/self/fd/1` -- стандартный поток вывода текущего процесса.

/dev/stderr::
Симлинка на `/proc/self/fd/2` -- стандартный поток ошибок текущего процесса.

== Read more

* https://media.ccc.de/v/32c3-7441-the_plain_simple_reality_of_entropy[Random & urandom devices (C) Filippo Valsorda at 32C3]
* https://www.linuxjournal.com/article/2890[Block devices (C) Linux journal]
* https://tldp.org/LDP/khg/HyperNews/get/devices/devices.html[Device drivers (C) KHG]
* https://www.reddit.com/r/hardware/comments/b0zb64/ssd_pcie_vs_sata_real_difference_for_programming/[PCI VS SATA (C) Reddit]

