= Filesystem Hierarchy Standard
:page-pagination:
:page-authors: Иван Калинин
:description: Filesystem Hierarchy Standard (Linux)

*Filesystem Hierarchy Standard (FHS)* - это соглашение об устройстве файловой системы Linux, использующееся в большинстве популярных дистрибутивов Linux. Однако, есть дистрибутивы не следующие ему. Таким, например, является https://nixos.org/[NixOS]. Информацию про FHS можно прочитать в мануале:
[,console]
----
$ man hier
----

== Три уровня бинарей

// TODO
[WARNING.todo]
====
Нужна ссыль на mounting process
====
Есть три папки, повторяющие структуру друг друга: `/`, `/usr`, `/usr/local`. Корневая папка используется для хранения файлов, необходимых для запуска или починики системы, в частности тут должны храниться файлы, доступные до момента монтирования файловых систем, отличных от корневой (`/`). Директории `/usr` и `/usr/local` уже содержат все остальные файлы, с которыми пользователь будет работать. Их отличие заключается в большинстве случаев в том, что `/usr` управляется пакетным менеджером системы (`dnf`, `apt`, etc.), а `/usr/local` предназначен для ручной установки.

CAUTION: То, что `/usr` управляется системой, не означает, что вы не можете вручную менять файлы в этой папке. Однако, следует быть аккуратным, чтобы не наделать конфликтов.

Каждая из директорий содержит следующие подпапки:

* `bin` -- бинарники: команды для работы в консоли (e.g. _ls_)
* `sbin` -- системные бинари (e.g. _reboot_)
* `lib` -- библиотеки (e.g. _libc_)
** `lib32` -- 32-битный код
** `lib64` -- 64-битный код
* `include` -- хедеры (e.g. _math.h_)
* `share` -- файлы, не зависящие от архитектуры. В эту папку перенесли различные поддиректории, ранее лежавшие рядом с `bin`

NOTE: Во многих новых дистрибутивах Linux папки `/bin`, `/lib`, `/sbin` не являются настоящими папками. На самом деле они -- симлинки на соответствующие папки в `/usr`. А `/usr/sbin` может быть симлинкой на `/usr/bin`.

=== Папка `share`
doc::
Внутри подпапки `doc` располагается различная документация проекта: это могут быть лицензии, README файлы. Для каждого инструмента такие данные собраны в директорию, которая имеет название инструмента. Например, для `zsh` собрана такая информация:

[,console]
----
$ ls /usr/share/doc/zsh
BUGS  completion-style-guide  CONTRIBUTORS FAQ  FEATURES
LICENCE  MACHINES  NEWS README  zsh-development-guide
----

man::
В этой подпапке собраны man страницы. Для каждого языка лежит своя подпапка, например, для итальянского -- `it`.

[TIP.todo]
====
Ссылка на маны
====

== Основные директории системы

_Все директории ниже лежат в корневой папке._

boot::
Статические бинарники для загрузчика системы. Сам загрузчик должен лежать либо в корне, либо в этой папке.

dev::
Расшифровывается как _devices_. Здесь собраны файлы устройств. Подробнее о папке `dev` написано xref:linux/devices.adoc[тут].

etc::
Расшифровывается как _et cetera_. Здесь располагаются конфигурационные файлы, например, `/etc/passwd`

// TODO
[TIP.todo]
====
ссыли на прокфс & сисфс
====

proc::
Точка монтирования _procfs_.

sys::
Точка монтирования _sysfs_.

lost+found::
"Потерянные" файлы.

// TODO
[TIP.todo]
====
больше про лост+фаунд
====

mnt::
Расшифровывается как _mount_. Точка монтирования временных файловых систем, например, live образ ОС при установке.

home::
В этой папке располагаются домашние директории пользователей. Обычно для каждого пользователя своя директория с соответствующим именем, однако можно выбрать любое название.

root::
Домашняя папка для рута.

tmp::
Расшифровывается как _temporary_. Хранилище временных файлов, которые можно удалить в любой момент времени.

opt::
Расшифровывается как _optional_. Различные приложения и расширения для системы.

run::
Расшифровывается как _runtime_. Описывает систему с момента запуска. Раньше для этого использовали `/var/run`, поэтому теперь этот файл является симлинкой на `/run`.

var::
Расшифровывается как _variable_. Данные, изменяющиеся в процессе работы системы.

=== Папка `run`

cache::
Кэши программ. Для каждой программы выделяется своя подпапка.

lib::
Переменные данные различных программ. Аналогично, для каждой программы своя подпапка.

[,console]
----
$ sudo ls /var/lib/docker
buildkit  containers  engine-id  image	network
plugins  policy  rootfs  runtimes  swarm  tmp	volumes
----

local::
Папка `var` для `/usr/local`.

opt::
Папка `/var` для `/opt`.

lock::
Тут хранятся lock-файлы.

// TODO
[TIP.todo]
----
Надо написать про лок файлы
----

log::
Логи различных программ

mail::
Почты пользователей.

== Команды

Данный стандарт не только фиксирует названия и назначения директорий, но еще и требует наличие определенных файлов, которые должны выполнять определенные цели. Так в `/bin` требуется наличие файлов `kill`, `mkdir`, `more`, `su` и других.

== Read more

* https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html[FHS 3.0 (C) Linux Foundation]
