= Filesystem Hierarchy Standard
:page-pagination:
:page-authors: Иван Калинин

*Filesystem Hierarchy Standard (FHS)* - это соглашение об устройстве файловой системы Linux, использующееся в большинстве популярных дистрибутивов Linux. Однако, есть дистрибутивы не следующие ему. Таким, например, является https://nixos.org/[NixOS]. Информацию про FHS можно прочитать в мануале:
[,console]
----
$ man hier
----

== Три уровня бинарей

// TODO
[WARNING.todo]
====
Нужна ссыль на mounting process
====
Есть три папки, повторяющие структуру друг друга: `/`, `/usr`, `/usr/local`. Корневая папка используется для хранения файлов, необходимых для запуска или починики системы, в частности тут должны храниться файлы, доступные до момента монтирования файловых систем, отличных от корневой (`/`). Директории `/usr` и `/usr/local` уже содержат все остальные файлы, с которыми пользователь будет работать. Их отличие заключается в большинстве случаев в том, что `/usr` управляется пакетным менеджером системы (`dnf`, `apt`, etc.), а `/usr/local` предназначен для ручной установки.

CAUTION: То, что `/usr` управляется системой, не означает, что вы не можете вручную менять файлы в этой папке. Однако, следует быть аккуратным, чтобы не наделать конфликтов.

Каждая из директорий содержит следующие подпапки:

* `bin` -- бинарники: команды для работы в консоли (e.g. _ls_)
* `sbin` -- системные бинари (e.g. _reboot_)
* `lib` -- библиотеки (e.g. _libc_)
** `lib32` -- 32-битный код
** `lib64` -- 64-битный код
* `include` -- хедеры (e.g. _math.h_)
* `share` -- файлы, не зависящие от архитектуры. В эту папку перенесли различные поддиректории, ранее лежавшие рядом с `bin`

NOTE: Во многих новых дистрибутивах Linux папки `/bin`, `/lib`, `/sbin` не являются настоящими папками. На самом деле они -- симлинки на соответствующие папки в `/usr`. А `/usr/sbin` может быть симлинкой на `/usr/bin`.

=== Папка `share`
doc::
Внутри подпапки `doc` располагается различная документация проекта: это могут быть лицензии, README файлы. Для каждого инструмента такие данные собраны в директорию, которая имеет название инструмента. Например, для `zsh` собрана такая информация:

[,console]
----
$ ls /usr/share/doc/zsh
BUGS  completion-style-guide  CONTRIBUTORS FAQ  FEATURES
LICENCE  MACHINES  NEWS README  zsh-development-guide
----

man::
В этой подпапке собраны man страницы. Для каждого языка лежит своя подпапка, например, для итальянского -- `it`.

[TIP.todo]
====
Ссылка на маны
====



== Read more

* https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html[FHS 3.0 (C) Linux Foundation]
