= Filesystem Hierarchy Standard
:page-pagination:
:page-authors: Иван Калинин

*Filesystem Hierarchy Standard (FHS)* - это соглашение об устройстве файловой системы Linux, использующееся в большинстве популярных дистрибутивов Linux. Однако, есть дистрибутивы не следующие ему. Таким, например, является https://nixos.org/[NixOS]. Информацию про FHS можно прочитать в мануале:
[,console]
----
$ man hier
----

== Три уровня бинарей

Есть три папки, повторяющие структуру друг друга: `/`, `/usr`, `/usr/local`. Корневая папка используется для хранения файлов, необходимых для запуска или починики системы, в частности тут должны храниться файлы, доступные до момента монтирования файловых систем, отличных от корневой (`/`). Директории `/usr` и `/usr/local` уже содержат все остальные файлы, с которыми пользователь будет работать. Их отличие заключается в большинстве случаев в том, что `/usr` управляется пакетным менеджером системы (`dnf`, `apt`, etc.), а `/usr/local` предназначен для ручной установки.

CAUTION: То, что

// TODO
[WARNING.todo]
====
Нужна ссыль на mounting process
====
Каждая из директорий содержит следующие подпапки:

* `bin` -- бинарники: команды для работы в консоли (e.g. _ls_)
* `sbin` -- системные бинари (e.g. _reboot_)
* `lib` -- библиотеки (e.g. _libc_)
** `lib32` -- 32-битный код
** `lib64` -- 64-битный код
* `include` -- хедеры (e.g. _math.h_)
* `share` --



== Read more

* https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html[FHS 3.0 (C) Linux Foundation]
