= Типы файлов
:page-pagination:
:page-authors: Иван Калинин
:description: Типы файлов в Linux

В Linux есть 7 типов файлов: регулярные, директории, ссылки, сокеты и пайпы, блочные и символьные устройства.

WARNING: Рекомендуем выполнять примеры кода внутри папки `/tmp` (убедитесь, что она смонтирована на `tmpfs`)

== Regular

*Регулярные файлы* или просто файлы -- это просто набор байт, который хранит какую-то информацию. Чтобы создать файл с некоторым содержимым, можно использовать конструкцию `echo CONTENT > FILENAME` или можно создать пустой файл с помощью команды `touch FILENAME`. Такие файлы в `ls -l` будут отображаться как `-`.

CAUTION: Команда `touch` прежде всего нужна для обновления информации о времени доступа и изменения файла.

== Directory
*Директории* или папки -- это узлы в файловой системе, которые содержат список других _вложенных_ файлов. Такие файлы в `ls -l` будут отображаться как `d`, также они часто окрашены в синий цвет.

Создать директорию можно с помощью команды `mkdir DIRNAME`. Если вам необходимо вместе с папкой создать еще ее родителей, то используйте флаг `-p`.

[,console]
----
$ mkdir folder/subfolder
mkdir: cannot create directory ‘folder/subfolder’: No such file or directory
$ mkdir -p folder/subfolder
$ ls folder
subfolder
----

== Links

*Ссылочные* файлы или символические ссылки (симлинки) -- это файлы, хранящие в себе путь до другого файла. При использовании такого файла ОС будет сама подставлять заместо него файл, на который указывает записанный путь. Такие файлы в `ls -l` будут отображаться как `l`, также они часто окрашены в циановый цвет.

Создать симлинку можно с помощью команды `ln -s PATH LINKNAME`. Прочесть содержимое самой симлинки можно с помощью `readlink`.


[,console]
----
$ ls subfolder
file.txt
$ ln -s subfolder/file.txt symlink
$ ls -l
drwxr-xr-x. nbah nbah 60 B Thu Jun 18 21:44:45 2026 subfolder
lrwxrwxrwx. nbah nbah 18 B Thu Jun 18 21:45:44 2026 symlink => subfolder/file.txt
$ readlink symlink
subfolder/file.txt
$ bat symlink
─────┬───────────────────────────────
     │ File: symlink
─────┼───────────────────────────────
   1 │ 4
─────┴───────────────────────────────
----

== Named pipes

*Именованные пайпы* -- это специальный вид файлов, позволяющий двум процессам отправлять сообщения. Пайп работает как односторонний канал отправки информации: существует только один слушатель, но при этом отправителей может быть несколько. Такие файлы в `ls -l` будут отображаться как `p`, также они часто окрашены в бледно-желтый цвет.

Для создания таких файлов используется команда `mkfifo PIPENAME`.

[,console]
----
$ mkfifo npipe
$ ls -l
prw-r--r--. nbah nbah 0 B Thu Jun 25 12:40:30 2026 npipe
----

Операции записи и чтения являются блокирующими. Это означает, что если на одном конце никого нет, то процесс на другом конце будет ждать пока кто-то не придет. Попробуем сделать запись в пайп: `echo Hello > npipe`. Заметим, что терминал "завис", тогда откроем второй терминал и попробуем прочитать файл: `cat npipe`. В этот же момент первый терминал проснулся, а во втором вывелось `Hello`. Аналогично произойдет, если сделать наоборот.

При одновременной записи в пайп больших размеров данных никаких гарантий на порядок данные не предоставляется. Откроем один терминал и в нем создадим три файла с 100тыс строк:
[.wrap,console]
----
$ for sym in a b c d e; do yes ${sym} | head -n 100000 > ${sym}.in; done
----
После попробуем записать их в пайп:
[.wrap,console]
----
$ for sym in a b c d e; do cat ${sym}.in > npipe & ; done
----
Теперь в другом терминале запустим команду: `cat npipe | uniq -d`. Она прочтет из пайпа и "схлопнет" последовательные дубликаты в один символ.

.Возможные результаты
[%collapsible]
====
В первый раз получим: +
`a c b c d e b c d e b c d e b d e`

Во второй раз получим: +
`d e d e b a c d e b a c d b a c b a c`
====

== Sockets
// TODO
[TIP.todo]
====
Пупупу
====

== Devices

Файлы *устройств* представляют собой интерфейсы взаимодействия с устройствами, как если бы они были файлами. Они подразделяются на два вида: *блочные* (block)  и *символьные* (character). Первые предоставляют буферизированный случайный доступ (buffered random access), когда как вторые предоставляют прямой доступ и не обязаны RA-устройствами. Также файловые системы могут быть смонтированы только на блочные устройства. Такие файлы в `ls -l` будут отображаться как `b` и `c`, a окрашены будут в бледно-желтый цвет.

Подробно о девайсах описано xref:linux/devices.adoc[тут].


// == Read more

