= Типы файлов
:page-pagination:
:page-authors: Иван Калинин

В Linux есть 7 типов файлов: регулярные, директории, ссылки, сокеты и пайпы, блочные и символьные устройства.

== Regular

*Регулярные файлы* или просто файлы -- это просто набор байт, который хранит какую-то информацию. Чтобы создать файл с некоторым содержимым, можно использовать конструкцию `echo CONTENT > FILENAME` или можно создать пустой файл с помощью команды `touch FILENAME`. Такие файлы в `ls -l` будут отображаться как `-`.

CAUTION: Команда `touch` прежде всего нужна для обновления информации о времени доступа и изменения файла.

== Directory
*Директории* или папки -- это узлы в файловой системе, которые содержат список других _вложенных_ файлов. Такие файлы в `ls -l` будут отображаться как `d`.

Создать директорию можно с помощью команды `mkdir DIRNAME`. Если вам необходимо вместе с папкой создать еще ее родителей, то используйте флаг `-p`.

[,console]
----
$ mkdir folder/subfolder
mkdir: cannot create directory ‘folder/subfolder’: No such file or directory
$ mkdir -p folder/subfolder
$ ls folder
subfolder
----

== Links

*Ссылочные* файлы или символические ссылки (симлинки) -- это файлы, хранящие в себе путь до другого файла. При использовании такого файла ОС будет сама подставлять заместо него файл, на который указывает записанный путь. Такие файлы в `ls -l` будут отображаться как `l`.

Создать симлинку можно с помощью команды `ln -s PATH LINKNAME`. Прочесть содержимое самой симлинки можно с помощью `readlink`.


[,console]
----
$ ls subfolder
file.txt
$ ln -s subfolder/file.txt symlink
$ ls -l
drwxr-xr-x. nbah nbah 60 B Thu Jun 18 21:44:45 2026 subfolder
lrwxrwxrwx. nbah nbah 18 B Thu Jun 18 21:45:44 2026 symlink => subfolder/file.txt
$ readlink symlink
subfolder/file.txt
$ bat symlink
─────┬───────────────────────────────
     │ File: symlink
─────┼───────────────────────────────
   1 │ 4
─────┴───────────────────────────────
----

